name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repos
        uses: actions/checkout@v3

      - name: Setup Noedejs
        uses: actions/setup-nodejs@v3

      - name: Install dependencies
        run: make install

      - name: Make lint
        run: make lint

        - name: Publish code coverage
          uses: paambaati/codeclimate-action@v5.0.0
          env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: src/main/java
          with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco